### PR TITLE
SNIP-9: Adding a new Cairo-2 compatible version for OutsideExecution type hashing

### PR DESCRIPTION
**Pull request by maorveitsman**
This change is [Reviewable](https://reviewable.io/reviews/starknet-io/SNIPs/76)

### CODE REVIEW

**Comment by sgc-code** [comment]
It would make sense to have a new interface ID. Accounts could implement both versions (or just one) and dapps could be able to tell what's supported by the account. To achieve that i propose renaming the cairo methods `execute_from_outside` to `execute_from_outside_v2`?, And the same for the other external method

**Review by florian-bellotti — APPROVED** [review]

**Comment by sgc-code** [comment]
For revision I suggest the following:
```
  OutsideExecution: [
    { name: "Caller", type: "ContractAddress" },
    { name: "Nonce", type: "felt" },
    { name: "Execute After", type: "u128" },
    { name: "Execute Before", type: "u128" },
    { name: "Calls", type: "Call*" },
  ],
  Call: [
    { name: "To", type: "ContractAddress" },
    { name: "Selector", type: "selector" },
    { name: "Calldata", type: "felt*" },
  ]
```

There are two changes here:
- replace u64 with u128, as u64 is not supported by SNIP-12. It still can (and should) be a u64 in the cairo struct
- replace snake_case with "Human Friendly Text": following the spirit of SNIP-12 rev1

There is also an additional change that needs to be done to be compliant with SNIP-12 rev1. That's escaping the names with quotes (JSON escape) as mentioned here https://github.com/starknet-io/SNIPs/blob/main/SNIPS/snip-12.md#specification That will generate different type hashes
For instance the Call will be encoded as:
`starknet_keccak('Call("To":"ContractAddress","Selector":"selector","Calldata":"felt*")')`

**Review by ArielElp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/SNIPs/76)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @AbdelStark, @bbrandtom, and @maorveitsman)

___
*[`SNIPS/snip-9.md` line 93 at r3](https://reviewable.io/reviews/starknet-io/SNIPs/76#-NpElo2T-NmAxzP-xKRU:-NpElo2T-NmAxzP-xKRV:b-g4psko) ([raw file](https://github.com/starknet-io/SNIPs/blob/bde40dc3a86425f191730ee6a33bdc76787e42f0/SNIPS/snip-9.md#L93)):*
> changed to type `u128`

The serialization is the same for all units < 256bit, can we keep u64 in version 2 and be compatible with the suggested interface?
IMO we should have it u64 here and have another revision to SNIP-12 that adds u64
___
*[`SNIPS/snip-9.md` line 199 at r3](https://reviewable.io/reviews/starknet-io/SNIPs/76#-NpEl7ftCCskOuCqTHR1:-NpEl7ftCCskOuCqTHR2:bjrk4s3) ([raw file](https://github.com/starknet-io/SNIPs/blob/bde40dc3a86425f191730ee6a33bdc76787e42f0/SNIPS/snip-9.md#L199)):*
> This method allows reentrancy

WDYM? the OutsideExecution struct has nonce, perhaps the wording should be that it is up to the account to guard against reentrancy on outside calls?
___
*[`SNIPS/snip-9.md` line 206 at r3](https://reviewable.io/reviews/starknet-io/SNIPs/76#-NpEmZfg6PXuQMKexXga:-NpEmZfg6PXuQMKexXgb:b-ilmogh) ([raw file](https://github.com/starknet-io/SNIPs/blob/bde40dc3a86425f191730ee6a33bdc76787e42f0/SNIPS/snip-9.md#L206)):*
> Array<felt252>

Cairo v2.5.0 introduced an optimization in `deserialize` of felt spans (constant cost versus having to loop over the array). `deserialize` is called whenever we call an external function (to convert the raw calldata to the contract entry point types), so I think taking that into account here.

**Review by yoga-braavos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/starknet-io/SNIPs/76)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @AbdelStark, @ArielElp, and @bbrandtom)

___
*[`SNIPS/snip-9.md` line 93 at r3](https://reviewable.io/reviews/starknet-io/SNIPs/76#-NpElo2T-NmAxzP-xKRU:-NpJHlGN919v-fvGCABJ:bjqigxd) ([raw file](https://github.com/starknet-io/SNIPs/blob/bde40dc3a86425f191730ee6a33bdc76787e42f0/SNIPS/snip-9.md#L93)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

> changed to type `u128`

The serialization is the same for all units < 256bit, can we keep u64 in version 2 and be compatible with the suggested interface?
IMO we should have it u64 here and have another revision to SNIP-12 that adds u64
</blockquote></details>

As discussed, since this is actually a change to SNIP-12 and there are different opinions about adding u64 to it, it was decided to leave this as-is for now
___
*[`SNIPS/snip-9.md` line 199 at r3](https://reviewable.io/reviews/starknet-io/SNIPs/76#-NpEl7ftCCskOuCqTHR1:-NpJHxu65MmGe2iSydy7:bd5h4s) ([raw file](https://github.com/starknet-io/SNIPs/blob/bde40dc3a86425f191730ee6a33bdc76787e42f0/SNIPS/snip-9.md#L199)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

> This method allows reentrancy

WDYM? the OutsideExecution struct has nonce, perhaps the wording should be that it is up to the account to guard against reentrancy on outside calls?
</blockquote></details>

Clarified the comment - it is re-entrant by definition, doesn't mean it is vulnerable to reentrancy attack if implemented correctly (sig and nonce are verified)
___
*[`SNIPS/snip-9.md` line 206 at r3](https://reviewable.io/reviews/starknet-io/SNIPs/76#-NpEmZfg6PXuQMKexXga:-NpJIb7mE3mistBxA313:bb7f2mf) ([raw file](https://github.com/starknet-io/SNIPs/blob/bde40dc3a86425f191730ee6a33bdc76787e42f0/SNIPS/snip-9.md#L206)):*
<details><summary><i>Previously, ArielElp wrote…</i></summary><blockquote>

> Array<felt252>

Cairo v2.5.0 introduced an optimization in `deserialize` of felt spans (constant cost versus having to loop over the array). `deserialize` is called whenever we call an external function (to convert the raw calldata to the contract entry point types), so I think taking that into account here.
</blockquote></details>

done

**Review by ArielElp — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/starknet-io/SNIPs/76#-:-NpKaMYN3a1m4TRUmJZG:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @AbdelStark and @bbrandtom)

**Pull request merged**
