### PR TITLE
SNIP-14: Non-fungible Tokenbound Accounts

### PR DESCRIPTION
**Pull request by Darlington02**

### CODE REVIEW

**Comment by Darlington02** [comment]
@ArielElp @AbdelStark still no updates:(

**Comment by Darlington02** [comment]
@AbdelStark @ArielElp

**Comment by Darlington02** [comment]
..

**Comment by dor-starkware** [comment]
Hi @Darlington02,

Thank you for your submission. After reviewing SNIP-72, we have a couple of points that need addressing to comply with the SNIP-1 guidelines:

1. **Date Format:** The creation date has a small typo. Please correct it to "2024-01-08".

2. **External Links**: According to SNIP-1, external links should be avoided as they can disappear or change unexpectedly.
Instead, please include any images, diagrams, and auxiliary files directly within a subdirectory of the assets folder for this SNIP. The path should be assets/snip-13, and you should use relative links such as ../assets/snip-13/image.png when linking to these files.

Once these changes are made, we can proceed with the review process.

**Comment by Darlington02** [comment]
thank you @dor-starkware. would we also be renaming to snip-13?

**Comment by leo-starkware** [comment]
@Darlington02 We merged snip-13 recently, so this would be snip-14

**Comment by Darlington02** [comment]
> Hi @Darlington02,
> 
> Thank you for your submission. After reviewing SNIP-72, we have a couple of points that need addressing to comply with the SNIP-1 guidelines:
> 
> 1. **Date Format:** The creation date has a small typo. Please correct it to "2024-01-08".
> 2. **External Links**: According to SNIP-1, external links should be avoided as they can disappear or change unexpectedly.
>    Instead, please include any images, diagrams, and auxiliary files directly within a subdirectory of the assets folder for this SNIP. The path should be assets/snip-13, and you should use relative links such as ../assets/snip-13/image.png when linking to these files.
> 
> Once these changes are made, we can proceed with the review process.

Hi @dor-starkware I've fixed all these:)

**Comment by Darlington02** [comment]
Hey @dor-starkware pinging about this. Any updates?

**Comment by dor-starkware** [comment]
Hey @Darlington02,

Sorry for the delay. This branch has now been merged.

**Pull request merged**
