### PR TITLE
SNIP-17: Safe Transfer for Fungible Tokens

### PR DESCRIPTION
**Pull request by boyuanx**
DIscussion: https://community.starknet.io/t/snip-89-safe-transfer-for-fungible-tokens/

### CODE REVIEW

**Comment by dor-starkware** [comment]
Hi @boyuanx,

As per SNIP-1 guidelines, there are a few elements that need to be addressed in SNIP-89 before it can move forward:

**Preamble Issues**:

- snip: - should be updated with the SNIP number.

- discussions-to: - should be updated with the discussion URL.

- created: 2024-6-24 should be corrected to 2024-06-24.

**Rationale**: This section is mandatory and should provide a detailed explanation of the design decisions made. It should also discuss any alternate designs considered and why they were not chosen, as well as related work in other languages or standards. For example, you can explain why the interface checks were implemented this way and what alternatives were considered.

**Backwards Compatibility**: This section is also mandatory if the SNIP introduces backwards incompatibilities. If there are no such incompatibilities, this should be explicitly stated. If there are any, please describe them and explain how they will be mitigated.

Please make these updates to comply with the SNIP-1 guidelines. Once these sections are added, we can proceed with the review process.

Thank you!

**Comment by boyuanx** [comment]
@dor-starkware Please check again, thanks!

**Comment by boyuanx** [comment]
Also, we can have a discussion on whether to use `Array` or `Span` for the input argument [here](https://github.com/boyuanx/starknet-erc20-safetransfer/blob/main/src/lib.cairo#L14).

**Comment by boyuanx** [comment]
Bump

**Comment by dor-starkware** [comment]
Hi @boyuanx,

Thank you for your patience. I’ve reviewed your recent commits and have a few minor requests before proceeding with the merge:

1. Could you please update the "Implementation" section to "Reference Implementation" to ensure consistency in section titles?
2. Similarly, please revise the "Security" section to "Security Considerations" for uniformity.
3. Additionally, in the preamble section, please update the SNIP number to 17.

Thank you!

**Comment by boyuanx** [comment]
@dor-starkware please check again, thanks!

**Comment by dor-starkware** [comment]
Hi @boyuanx,

Thank you for making the necessary adjustments to the SNIP. I noticed that there are links in the document that are supposed to lead to the SNIP-17 page (which corresponds to this SNIP). However, these links currently lead to a non-existent page, resulting in a 404 error. Could you please remove these links?

Additionally, could you please change the status in the preamble from 'Draft' to 'Review'?

Once these changes are made, I’ll proceed with merging your SNIP into the main branch.

Thank you!

**Comment by boyuanx** [comment]
@dor-starkware I have made those changes, please check :)

**Pull request merged**
