### PR TITLE
SNIP-64: Custom Errors for Fungible and Non-Fungible Tokens

### PR DESCRIPTION
**Pull request by boyuanx**
DIscussion: https://community.starknet.io/t/snip-custom-errors-for-fungible-and-non-fungible-tokens/109592

### CODE REVIEW

**Comment by boyuanx** [comment]
If SNIP-63 passes, this one will be renamed to SNIP-E6093

**Comment by boyuanx** [comment]
Another point of discussion:

If we think storing error strings is too expensive, we can consider giving them IDs and store that instead.

**Review by abdelhamidbakhta — CHANGES_REQUESTED** [review]
change SNIP number to 64

**Review by abdelhamidbakhta — APPROVED** [review]
lgtm

**Pull request merged**
