### PR TITLE
SNIP-59: Sign-In with Starknet

### PR DESCRIPTION
**Pull request by boyuanx**
Discussion link pending.

### CODE REVIEW

**Comment by boyuanx** [comment]
> A sign-in with Starknet proposal is already being discussed [here](https://community.starknet.io/t/sign-in-with-starknet-technical-proposal/95683/5), along with an implementation. Very glad to see another person pushing for this. I don't see any significant difference with the one on the forums, if there is consensus there let's combine the best parts of both and move it forward.
> 
> My main issue is that a data encoding standard doesn't exist yet. We should probably design that first.

No idea why this never showed up when I Google'd "sign in with starknet", happy to combine and move forward :)

**Review by abdelhamidbakhta — APPROVED** [review]
change SNIP number to 59

**Review by abdelhamidbakhta — CHANGES_REQUESTED** [review]
change SNIP number to 59

**Comment by boyuanx** [comment]
Closing this in favor of @ FawadHa1der 's post here: https://community.starknet.io/t/sign-in-with-starknet-technical-proposal/95683

**Pull request closed without merging**
